name: Deploy
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
#        run: |
#          git config user.name github-actions[bot]
#          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#
      - name: Setup python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
#      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: mkdocs build

#      - name: Deploy to Github Pages
#        run: mkdocs gh-deploy --force
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Deploy Sphinx docs for ${{ github.sha }}"